config/routes.rb
Rails.application.routes.draw do
  resources :passwords,
            controller: 'clearance/passwords',
            only: [:create, :new]

  resource :session,
           controller: 'clearance/sessions',
           only: [:create]

  resources :users,
            only: Clearance.configuration.user_actions do
    resource :password,
             controller: 'clearance/passwords',
             only: [:create, :edit, :update]
  end

  resources :books_group_has_book, only: [:destroy]

  resources :advertisements do
    resources :books_group_has_book
  end

  get '/my_advertisements' => 'advertisements#user_advertisements', as: 'my_advertisements'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  root to: 'advertisements#index'
  if Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#new', as: 'sign_up'
  end

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :books_group
  has_many :books_group_has_books, through: :books_group
  has_many :books, through: :books_group_has_books
  belongs_to :user

  validate :ativo?

  private

  def ativo?
    errors.add(:ativo, 'needs at least one book') if ativo && books.size.zero?
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :require_login, only: [:user_advertisements]
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.where(ativo: true)
  end

  def user_advertisements
    @advertisements = Advertisement.where(user_id: current_user.id)
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
    @advertisement.user_id = current_user.id
    @advertisement.books_group = BooksGroup.create
    @advertisement.save
    # client = Mongo::Client.new([ '127.0.0.1:27017' ], :database => 'test')
    # collection = client[:advertisement]
    # collection.insert_one(relational_id: @advertisement.id)
    redirect_to edit_advertisement_path(@advertisement)
  end
  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)
    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update

    respond_to do |format|
      if @advertisement.update(advertisement_params)
        # client = Mongo::Client.new([ '127.0.0.1:27017' ], :database => 'test')
        # collection = client[:advertisement]
        # collection.update_one({relational_id: @advertisement.id}, { '$set' => { descricao: @advertisement.descricao,  }})

        format.html { redirect_to edit_advertisement_path(@advertisement), notice: 'Advertisement was successfully updated.' }
        format.json { render :edit, status: :ok, location: @advertisement }
      else
        flash[:warning] = @advertisement.errors.full_messages
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:titulo, :descricao, :ativo)
    end

    def check_user
      return if @advertisement.user.id == current_user.id
      flash[:notice] = 'Unauthorized'
      redirect_to advertisement_path(@advertisement)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_form.html.erb
<%= form_for(@advertisement) do |form| %>
  <div class="actions">
    <div class="text-field text-center">

      <%= form.text_field :titulo, type: 'text', :class => "form-control", :placeholder => "Enter the title of the ad ... " %>
    </div>
    <br/>
    <div class="text-field text-center">

      <%= form.text_area :descricao, type: 'text', :class => "form-control", :placeholder => "Write a description of the advertisement ... " %>
    </div>

    <div class="text-field">
<br>
      <table border="0">
        <tr>
          <td>
            <%= form.submit "Save", :class => "btn btn-primary newBotton" %>
          </td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td>
<!-- Tentar fazer esse botão funcionar -->
            <button type="button" class="btn btn-success newBotton">Enable</button>
            <%= form.check_box :ativo %>
            <%= @ativo %>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/advertisements/_list.html.erb
<div id="gallery" class="gallery all_pad wthree">
  <div class="container">

    <h3 class="title">Advertisements  <%= link_to '+', new_advertisement_path if signed_in? %></h3>


    <br>
<% @advertisements.each do |advertisement| %>

<div class="col-md-4 gal-grid  wow bounceInUp" data-wow-duration="1.5s" data-wow-delay="3s" style="margin-bottom: 30px">
  <div class="gal-img">
    <%= link_to advertisement_path(advertisement) do %>
      <div class="item item-type-double">
        <div class="item-hover">
          <div class="item-info">
            <div class="line"></div>
            <div class="headline">More informations</div>
            <div class="line"></div>
          </div>
          <div class="mask"></div>
        </div>
        <div class="item-img"><%= image_tag "g1.jpg" %></div>
      </div>
    <% end %>

    <div class="text-center" style="padding-top: 10px">
    <h4> <%= advertisement.titulo %></h4>

    <br/>
      <%= link_to 'EDIT', edit_advertisement_path(advertisement), :class => "btn btn-warning"  if signed_in? && current_user.id == advertisement.user_id %>
      <%= link_to 'DELETE', advertisement_path(advertisement), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } if signed_in? && current_user.id == advertisement.user_id %>
      <br/><br/>

    </div>


  </div>
</div>
<% end %>
  </div>
</div>

app/views/advertisements/edit.html.erb
<div id="gallery" class="gallery all_pad wthree">
  <div class="container">

<h3 class="title">Editing Advertisement</h3>

<%= render 'form' %>

<h3 class="title">Books of this ad <%= link_to '+', new_advertisement_books_group_has_book_path(@advertisement) %></h3>
    <%= link_to 'Show', @advertisement %> |
    <%= link_to 'Back', advertisements_path %>
    <br><br>
<table class="table">
    <tr>
      <th>Title</th>
      <th>New / Used</th>
      <th>Publication Year</th>
    </tr>
  <% @advertisement.books_group_has_books.each do |book| -%>
    <tr>
      <td><%= book.book.titulo %></td>
      <td><%= book.estado %></td>
      <td><%= book.ano_compra %></td>
      <td><%= link_to 'x', books_group_has_book_path(book, return_url: edit_advertisement_path(@advertisement)), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br><br>

  </div>
</div>

app/views/advertisements/index.html.erb
<% content_for :search do %>

<%= form_tag url_for(:controller => 'advertisements', :action => 'index'), method: 'get' do -%>
  <div class="text-field contact-right">
    <%= text_field_tag :search, params[:search], class: 'form-control input-lg', :placeholder => 'Which book or collection do you look for?' %>
    <%= submit_tag :"LET'S GO!", name: nil %>
  </div>
<% end %>

<% end %>
<%= render 'list' %>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisements_path %>

app/views/advertisements/show.html.erb
<div id="gallery" class="gallery all_pad wthree">
  <div class="container">

    <h3 class="title"><%= @advertisement.titulo %></h3>

    <%= link_to 'Edit', edit_advertisement_path(@advertisement) if current_user == @advertisement.user %>
    |
    <%= link_to 'Back', advertisements_path %>
    <br><br>
    <p><%= @advertisement.descricao %></p>
    <br/>

    <table class="table">
      <tr>
        <th>Title</th>
        <th>New / Used</th>
        <th>Publication Year</th>
      </tr>
      <% @advertisement.books_group_has_books.each do |book| -%>
          <tr>
            <td><%= book.book.titulo %></td>
            <td><%= book.estado %></td>
            <td><%= book.ano_compra %></td>

          </tr>
      <% end %>
    </table>

    <br><br>

  </div>
</div>

app/views/advertisements/user_advertisements.html.erb
<%= render 'list' %>